### ISSUE TITLE
Gap analysis - overview

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdmkit#427]
**Topics to be described in RDMKit**

- [x] FAIR principles --> described in the About page √
- [x] Archiving, Cold vs Active storage --> data storage page √
- [x] Cloud?
- [x] Tiered storage; Grid storage
- [x] Informed consent, Data Transfer Agreement --> Human data √
- [x] Data Documentation
- [x] Identifiers (identifiers for evolving datasets)
- [x] Existing data (where to find, how to reuse) (#607 )
- [x] (bio)Containers
- [x] Costs for data management (#593 )
- [x] LIMS, ELN, EDC systems
- [x] definition of DATA in this RDMkit (#1252 )
- [ ] Distributed/Federated computing
- [x] Virtual research environment
- [ ] Management of collaborative research
- [ ] File format open vs proprietary
- [ ] Citing dataset and software
- [ ] RO-crate/FairDigitalObject
- [ ] Interoperability tools
- [ ] Tidy data, Data Carpentry, how to organise data table.
- [ ] Analysis workflow: Cloud execution and publication.
- [ ] How to manage software, software management
- [ ] Synthetic data
- [ ] AI
- [ ] Federated learning

**Tools or resources to be placed in the right context**

- [ ] EUDAT services
- [ ] ELIXIR platforms, services
- [x] FedEGA

**Comment by floradanna** [comment]
Related issue: https://github.com/elixir-europe/rdmkit/issues/364

**Comment by CaroleGoble** [comment]
More missing - 

- Notebooks (nearly all students and postdocs use ELNs as their data management platform/gateway and they barely get mentioned), 
- using Cloud service securely, 
- Synthetic data
-

**Comment by bedroesb** [comment]
@floradanna I think this issue can be closed, and can maybe be replaced by the topics we made for our last contentathon?

**Comment by bedroesb** [comment]
This issue will be closed and replaced by an updated one based on contentathon topics/tools that have no contect
