### ISSUE TITLE
UI/UX To Do - Idea list

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#447]
- [x] Having the sidepanel behind a hamburger menu in mobile mode (done in #477 )
- [x] Accessibility check ( #484 )
- [x] fix home page button problem on some MacOS devices (done in #466 )
- [x] Better search (content search) [lunr.js](lunrjs.com)  (done in #532  )
- [x] Using purge.css or similar to improve website speeds #675 
- [x] Moving to SCSS for better theme-ing #675 
    - [x] Consistent use/style of buttons #699 
- [ ] Changing sidenaviagtion library navgoco to not use jquery.cookie 
- [ ] Improved linking to tools/resources 
~Consider https://en.gravatar.com/ for profile images~
~References/paper section + icon~

**Comment by martin-nc** [comment]
Suggest we do an accessibility check as well:
https://www.gov.uk/government/publications/doing-a-basic-accessibility-check-if-you-cant-do-a-detailed-one/doing-a-basic-accessibility-check-if-you-cant-do-a-detailed-one

...and write an accessibility statement.

**Comment by bedroesb** [comment]
I will close this issue in favor of the new UX expert discussion so we can make new issues
